// This code was generated by RudementaryLathe on 10/6/2015 12:00:00 AM by version:1.0.5757.15819.
using System;
using System.Linq;

namespace ARCCv2.Contracts
{
    public interface IRepository<T> where T : class
    {
        IQueryable<T> GetAll();
        T GetById(int id);
        T GetById(string id);
        T GetById(int key1, int key2);
        T GetById(string key1, string key2);
        void Add(T entity);
        void Update(T entity);
        void Delete(T entity);
        void Delete(int id);
        void Delete(string id);
        void Delete(int key1, int key2);
        void Delete(string key1, string key2);
    }
}
