// This code was generated by RudementaryLathe on 10/6/2015 12:00:00 AM by version:1.0.5757.15819.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;

namespace ARCCv2.UnitTest
{
    [TestClass]
    public class ARCCv2SmokeTestViews : TestBase
    {
        [TestMethod]
        public void TestConnectionString()
        {
            try
            {
                var connection = System.Configuration.ConfigurationManager.ConnectionStrings["ARCCv2"];
                Assert.IsTrue(true, "Valid Connection String Detected");
            }
            catch (System.Configuration.ConfigurationErrorsException ex)
            {
                Assert.Fail("The ARCCv2 connection string is missing or invalid");
            }
        }

    }
}
