// This code was generated by RudementaryLathe on 10/6/2015 12:00:00 AM by version:1.0.5757.15819.
using ARCCv2.Data;

namespace ARCCv2.UnitTest
{
    public class TestBase
    {
        ARCCv2UOW arccv2Uow;

        protected ARCCv2UOW Uow
        {
            get
            {
                if (arccv2Uow == null)
                {
                    arccv2Uow = new ARCCv2UOW(new ARCCv2.Data.RepositoryProvider(new ARCCv2.Data.RepositoryFactories()));

                }
                return arccv2Uow;
            }
        }
    }
}
