// This code was generated by RudementaryLathe on 10/6/2015 12:00:00 AM by version:1.0.5757.15819.
using System;
using System.Data.Entity;
using System.Linq;
using ARCCv2.Contracts;
using ARCCv2.Models;

namespace ARCCv2.Data
{
    public partial class StatusRepository : EFRepository<Status>, IStatusRepository
    {
        public StatusRepository(DbContext context) : base(context) { }

    }
}
