// This code was generated by RudementaryLathe on 10/6/2015 12:00:00 AM by version:1.0.5757.15819.
using ARCCv2.Models;

namespace ARCCv2.Contracts
{
    public partial interface IARCCScoreRepository : IRepository<ARCCScore>
    {
    }
}
