// This code was generated by RudementaryLathe on 10/6/2015 12:00:00 AM by version:1.0.5757.15819.
using ARCCv2.Data.Configuration;
using ARCCv2.Models;
using System.Data.Entity;

namespace ARCCv2.Data
{
    public static class TableContexts
    {
        public static void AddTableConfigurations(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new ARCCHardwareBudgetMap());
            modelBuilder.Configurations.Add(new ARCCOtherBudgetMap());
            modelBuilder.Configurations.Add(new ARCCProposalMap());
            modelBuilder.Configurations.Add(new ARCCScoreMap());
            modelBuilder.Configurations.Add(new ARCCSoftwareBudgetMap());
            modelBuilder.Configurations.Add(new DeeHardwareBudgetMap());
            modelBuilder.Configurations.Add(new DeeOtherBudgetMap());
            modelBuilder.Configurations.Add(new DeeProposalMap());
            modelBuilder.Configurations.Add(new DeeScoreMap());
            modelBuilder.Configurations.Add(new DeeSoftwareBudgetMap());
            modelBuilder.Configurations.Add(new UserMap());
            modelBuilder.Configurations.Add(new UserTypeMap());
        }
    }
}
