// This code was generated by RudementaryLathe on 10/6/2015 12:00:00 AM by version:1.0.5757.15819.
using ARCCv2.Contracts;

namespace ARCCv2.Data
{
    public partial class ARCCv2UOW
    {
        public IARCCHardwareBudgetRepository ARCCHardwareBudgetRepository { get { return GetRepo<IARCCHardwareBudgetRepository>(); } }
        public IARCCOtherBudgetRepository ARCCOtherBudgetRepository { get { return GetRepo<IARCCOtherBudgetRepository>(); } }
        public IARCCProposalRepository ARCCProposalRepository { get { return GetRepo<IARCCProposalRepository>(); } }
        public IARCCScoreRepository ARCCScoreRepository { get { return GetRepo<IARCCScoreRepository>(); } }
        public IARCCSoftwareBudgetRepository ARCCSoftwareBudgetRepository { get { return GetRepo<IARCCSoftwareBudgetRepository>(); } }
        public IDeeHardwareBudgetRepository DeeHardwareBudgetRepository { get { return GetRepo<IDeeHardwareBudgetRepository>(); } }
        public IDeeOtherBudgetRepository DeeOtherBudgetRepository { get { return GetRepo<IDeeOtherBudgetRepository>(); } }
        public IDeeProposalRepository DeeProposalRepository { get { return GetRepo<IDeeProposalRepository>(); } }
        public IDeeScoreRepository DeeScoreRepository { get { return GetRepo<IDeeScoreRepository>(); } }
        public IDeeSoftwareBudgetRepository DeeSoftwareBudgetRepository { get { return GetRepo<IDeeSoftwareBudgetRepository>(); } }
        public IUserRepository UserRepository { get { return GetRepo<IUserRepository>(); } }
        public IUserTypeRepository UserTypeRepository { get { return GetRepo<IUserTypeRepository>(); } }
    }
}
