// This code was generated by RudementaryLathe on 10/6/2015 12:00:00 AM by version:1.0.5757.15819.
using System.Data.Entity;

namespace ARCCv2.Data
{
    public static class ViewContexts
    {
        public static void AddViewConfigurations(DbModelBuilder modelBuilder)
        {
        }
    }
}
