// This code was generated by RudementaryLathe on 10/6/2015 12:00:00 AM by version:1.0.5757.15819.
using ARCCv2.Contracts;
using ARCCv2.Data;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace ARCCv2.Data
{
    public class ViewRepositories
    {
        IDictionary<Type, Func<DbContext, object>> repositoryDictionary;

        public ViewRepositories(IDictionary<Type, Func<DbContext, object>> repositoryDictionary)
        {
            this.repositoryDictionary = repositoryDictionary;
        }

        public void AddViews()
        {
        }
    }
}
